-- migrate:up
CREATE TABLE ratings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ratings INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- migrate:down
DROP TABLE ratings
