language: generic
sudo: required
branches:
  only:
    - feature/docker
# services:
#   - docker
# before_install: # 패키지를 다운로드 받기 전
#   - docker build -t eunsongpark/project-gift-server .

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: project-gift-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: projectGift/server
      branch: feature/docker
