version: '3'

services:
  # nginx:
  #   restart: always
  #   image: ghcr.io/smileeunsong/project-gift-nginx
  #   # build:
  #   #   dockerfile: Dockerfile
  #   #   context: ./nginx
  #   container_name: app_nginx
  #   ports:
  #     - "80:80"
  #   mem_limit: 128m
  #   links:
  #     - frontend
  #     - backend

  backend:
    image: ghcr.io/smileeunsong/project-gift-server
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      PORT: 3000
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRESIN: $JWT_EXPIRESIN
    mem_limit: 128m
